// <auto-generated />
using System;
using AirCompany.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AirCompany.Infrastructure.Database.Migrations
{
    [DbContext(typeof(AirCompanyDbContext))]
    [Migration("20251027122110_AddData")]
    partial class AddData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AirCompany.Domain.Model.AircraftFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AircraftFamilies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Airbus",
                            Name = "A320 Family"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Boeing",
                            Name = "B737 Family"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Embraer",
                            Name = "E-Jet Family"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Airbus",
                            Name = "A330 Family"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Boeing",
                            Name = "B787 Family"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Airbus",
                            Name = "A350 Family"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Bombardier",
                            Name = "CRJ Family"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "Sukhoi",
                            Name = "Regional Jet Family"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Boeing",
                            Name = "B777 Family"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "Sukhoi",
                            Name = "SSJ Family"
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Model.AircraftModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CargoCapacityKg")
                        .HasColumnType("double precision");

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<double>("FlightRangeKm")
                        .HasColumnType("double precision");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PassengerCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("AircraftModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CargoCapacityKg = 20000.0,
                            FamilyId = 1,
                            FlightRangeKm = 6300.0,
                            ModelName = "A320neo",
                            PassengerCapacity = 180
                        },
                        new
                        {
                            Id = 2,
                            CargoCapacityKg = 23000.0,
                            FamilyId = 1,
                            FlightRangeKm = 8700.0,
                            ModelName = "A321XLR",
                            PassengerCapacity = 206
                        },
                        new
                        {
                            Id = 3,
                            CargoCapacityKg = 19000.0,
                            FamilyId = 2,
                            FlightRangeKm = 6500.0,
                            ModelName = "737MAX8",
                            PassengerCapacity = 175
                        },
                        new
                        {
                            Id = 4,
                            CargoCapacityKg = 20000.0,
                            FamilyId = 2,
                            FlightRangeKm = 5950.0,
                            ModelName = "737MAX10",
                            PassengerCapacity = 188
                        },
                        new
                        {
                            Id = 5,
                            CargoCapacityKg = 10000.0,
                            FamilyId = 3,
                            FlightRangeKm = 4400.0,
                            ModelName = "E190",
                            PassengerCapacity = 100
                        },
                        new
                        {
                            Id = 6,
                            CargoCapacityKg = 11000.0,
                            FamilyId = 3,
                            FlightRangeKm = 4800.0,
                            ModelName = "E195-E2",
                            PassengerCapacity = 124
                        },
                        new
                        {
                            Id = 7,
                            CargoCapacityKg = 45000.0,
                            FamilyId = 4,
                            FlightRangeKm = 11500.0,
                            ModelName = "A330-300",
                            PassengerCapacity = 277
                        },
                        new
                        {
                            Id = 8,
                            CargoCapacityKg = 50000.0,
                            FamilyId = 5,
                            FlightRangeKm = 13600.0,
                            ModelName = "B787-8",
                            PassengerCapacity = 242
                        },
                        new
                        {
                            Id = 9,
                            CargoCapacityKg = 60000.0,
                            FamilyId = 6,
                            FlightRangeKm = 15000.0,
                            ModelName = "A350-900",
                            PassengerCapacity = 300
                        },
                        new
                        {
                            Id = 10,
                            CargoCapacityKg = 8000.0,
                            FamilyId = 7,
                            FlightRangeKm = 2900.0,
                            ModelName = "CRJ900",
                            PassengerCapacity = 90
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalAirport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ArrivalDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("DepartureAirport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DepartureDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("FlightDuration")
                        .HasColumnType("interval");

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ModelId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalAirport = "LHR",
                            ArrivalDateTime = new DateTime(2025, 10, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1001",
                            DepartureAirport = "SVO",
                            DepartureDateTime = new DateTime(2025, 10, 1, 6, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 2, 0, 0, 0),
                            ModelId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArrivalAirport = "JFK",
                            ArrivalDateTime = new DateTime(2025, 10, 2, 17, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1002",
                            DepartureAirport = "SVO",
                            DepartureDateTime = new DateTime(2025, 10, 2, 11, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 6, 0, 0, 0),
                            ModelId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArrivalAirport = "CDG",
                            ArrivalDateTime = new DateTime(2025, 10, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1003",
                            DepartureAirport = "LED",
                            DepartureDateTime = new DateTime(2025, 10, 3, 5, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 3, 0, 0, 0),
                            ModelId = 3
                        },
                        new
                        {
                            Id = 4,
                            ArrivalAirport = "DXB",
                            ArrivalDateTime = new DateTime(2025, 10, 4, 16, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1004",
                            DepartureAirport = "VKO",
                            DepartureDateTime = new DateTime(2025, 10, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 6, 0, 0, 0),
                            ModelId = 4
                        },
                        new
                        {
                            Id = 5,
                            ArrivalAirport = "SIN",
                            ArrivalDateTime = new DateTime(2025, 10, 6, 2, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1005",
                            DepartureAirport = "SVO",
                            DepartureDateTime = new DateTime(2025, 10, 5, 18, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 8, 0, 0, 0),
                            ModelId = 5
                        },
                        new
                        {
                            Id = 6,
                            ArrivalAirport = "HND",
                            ArrivalDateTime = new DateTime(2025, 10, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1006",
                            DepartureAirport = "SVO",
                            DepartureDateTime = new DateTime(2025, 10, 6, 2, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 9, 0, 0, 0),
                            ModelId = 6
                        },
                        new
                        {
                            Id = 7,
                            ArrivalAirport = "BER",
                            ArrivalDateTime = new DateTime(2025, 10, 7, 9, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1007",
                            DepartureAirport = "LED",
                            DepartureDateTime = new DateTime(2025, 10, 7, 7, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 2, 0, 0, 0),
                            ModelId = 7
                        },
                        new
                        {
                            Id = 8,
                            ArrivalAirport = "LHR",
                            ArrivalDateTime = new DateTime(2025, 10, 8, 14, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1008",
                            DepartureAirport = "SVO",
                            DepartureDateTime = new DateTime(2025, 10, 8, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 2, 0, 0, 0),
                            ModelId = 8
                        },
                        new
                        {
                            Id = 9,
                            ArrivalAirport = "CDG",
                            ArrivalDateTime = new DateTime(2025, 10, 9, 7, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1009",
                            DepartureAirport = "VKO",
                            DepartureDateTime = new DateTime(2025, 10, 9, 4, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 3, 0, 0, 0),
                            ModelId = 9
                        },
                        new
                        {
                            Id = 10,
                            ArrivalAirport = "JFK",
                            ArrivalDateTime = new DateTime(2025, 10, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            Code = "SU1010",
                            DepartureAirport = "SVO",
                            DepartureDateTime = new DateTime(2025, 10, 10, 3, 0, 0, 0, DateTimeKind.Utc),
                            FlightDuration = new TimeSpan(0, 6, 0, 0, 0),
                            ModelId = 10
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateOnly(1985, 1, 10),
                            FullName = "Ivanov Ivan Ivanovich",
                            PassportNumber = "P100001"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateOnly(1990, 5, 22),
                            FullName = "Petrova Anna Sergeevna",
                            PassportNumber = "P100002"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateOnly(1978, 3, 15),
                            FullName = "Sidorov Peter Maximovich",
                            PassportNumber = "P100003"
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateOnly(1988, 11, 2),
                            FullName = "Smith John",
                            PassportNumber = "P100004"
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateOnly(1992, 7, 7),
                            FullName = "Brown Alice",
                            PassportNumber = "P100005"
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateOnly(1983, 12, 12),
                            FullName = "Taylor Robert",
                            PassportNumber = "P100006"
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateOnly(1995, 2, 28),
                            FullName = "Lee Kevin",
                            PassportNumber = "P100007"
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateOnly(1987, 6, 19),
                            FullName = "Kuznetsova Olga",
                            PassportNumber = "P100008"
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateOnly(1991, 9, 5),
                            FullName = "Nguyen Linh",
                            PassportNumber = "P100009"
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateOnly(1989, 8, 23),
                            FullName = "Garcia Maria",
                            PassportNumber = "P100010"
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateOnly(1975, 4, 1),
                            FullName = "Schmidt Hans",
                            PassportNumber = "P100011"
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateOnly(1982, 10, 14),
                            FullName = "Dubois Pierre",
                            PassportNumber = "P100012"
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateOnly(1986, 3, 17),
                            FullName = "Rossi Marco",
                            PassportNumber = "P100013"
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateOnly(1993, 12, 25),
                            FullName = "Silva Ana",
                            PassportNumber = "P100014"
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateOnly(1990, 5, 5),
                            FullName = "Novak Petra",
                            PassportNumber = "P100015"
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateOnly(1981, 9, 30),
                            FullName = "Kowalski Jan",
                            PassportNumber = "P100016"
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateOnly(1984, 11, 11),
                            FullName = "Popov Ivan",
                            PassportNumber = "P100017"
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateOnly(1989, 1, 20),
                            FullName = "Hernandez Luis",
                            PassportNumber = "P100018"
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateOnly(1992, 2, 2),
                            FullName = "Singh Raj",
                            PassportNumber = "P100019"
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateOnly(1986, 7, 15),
                            FullName = "Wang Li",
                            PassportNumber = "P100020"
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateOnly(1988, 6, 30),
                            FullName = "Muller Eva",
                            PassportNumber = "P100021"
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateOnly(1985, 8, 19),
                            FullName = "Nowak Adam",
                            PassportNumber = "P100022"
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateOnly(1991, 3, 27),
                            FullName = "Ivanova L.",
                            PassportNumber = "P100023"
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateOnly(1987, 10, 8),
                            FullName = "Petrov P.",
                            PassportNumber = "P100024"
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateOnly(1980, 12, 12),
                            FullName = "Gonzalez M.",
                            PassportNumber = "P100025"
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateOnly(1983, 5, 17),
                            FullName = "Anderson L.",
                            PassportNumber = "P100026"
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateOnly(1979, 11, 23),
                            FullName = "O'Neil K.",
                            PassportNumber = "P100027"
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateOnly(1994, 4, 2),
                            FullName = "Martinez C.",
                            PassportNumber = "P100028"
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateOnly(1985, 9, 12),
                            FullName = "Sato Y.",
                            PassportNumber = "P100029"
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateOnly(1989, 6, 6),
                            FullName = "Petrova M.",
                            PassportNumber = "P100030"
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightId")
                        .HasColumnType("integer");

                    b.Property<bool?>("HasHandLuggage")
                        .HasColumnType("boolean");

                    b.Property<int>("PassengerId")
                        .HasColumnType("integer");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<double?>("TotalBaggageWeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SeatNumber")
                        .IsUnique();

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 1,
                            SeatNumber = "12A",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 2,
                            SeatNumber = "12B",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 3,
                            SeatNumber = "13C",
                            TotalBaggageWeightKg = 15.0
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 1,
                            HasHandLuggage = true,
                            PassengerId = 4,
                            SeatNumber = "12C",
                            TotalBaggageWeightKg = 15.0
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 5,
                            SeatNumber = "14A",
                            TotalBaggageWeightKg = 20.0
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 2,
                            HasHandLuggage = true,
                            PassengerId = 6,
                            SeatNumber = "14B",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 2,
                            HasHandLuggage = false,
                            PassengerId = 7,
                            SeatNumber = "14C",
                            TotalBaggageWeightKg = 25.0
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 8,
                            SeatNumber = "10A",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 3,
                            HasHandLuggage = true,
                            PassengerId = 9,
                            SeatNumber = "10B",
                            TotalBaggageWeightKg = 10.0
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 3,
                            HasHandLuggage = false,
                            PassengerId = 10,
                            SeatNumber = "10C",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 11,
                            SeatNumber = "15A",
                            TotalBaggageWeightKg = 12.0
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 4,
                            HasHandLuggage = true,
                            PassengerId = 12,
                            SeatNumber = "15B",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 4,
                            HasHandLuggage = false,
                            PassengerId = 13,
                            SeatNumber = "15C",
                            TotalBaggageWeightKg = 8.0
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 5,
                            HasHandLuggage = true,
                            PassengerId = 14,
                            SeatNumber = "16A",
                            TotalBaggageWeightKg = 5.0
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 5,
                            HasHandLuggage = true,
                            PassengerId = 15,
                            SeatNumber = "16B",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 16,
                            FlightId = 5,
                            HasHandLuggage = false,
                            PassengerId = 16,
                            SeatNumber = "16C",
                            TotalBaggageWeightKg = 20.0
                        },
                        new
                        {
                            Id = 17,
                            FlightId = 6,
                            HasHandLuggage = true,
                            PassengerId = 17,
                            SeatNumber = "17A",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 18,
                            FlightId = 6,
                            HasHandLuggage = true,
                            PassengerId = 18,
                            SeatNumber = "17B",
                            TotalBaggageWeightKg = 25.0
                        },
                        new
                        {
                            Id = 19,
                            FlightId = 6,
                            HasHandLuggage = false,
                            PassengerId = 19,
                            SeatNumber = "17C",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 20,
                            FlightId = 7,
                            HasHandLuggage = true,
                            PassengerId = 20,
                            SeatNumber = "18A",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 21,
                            FlightId = 7,
                            HasHandLuggage = true,
                            PassengerId = 21,
                            SeatNumber = "18B",
                            TotalBaggageWeightKg = 5.0
                        },
                        new
                        {
                            Id = 22,
                            FlightId = 7,
                            HasHandLuggage = false,
                            PassengerId = 22,
                            SeatNumber = "18C",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 23,
                            FlightId = 8,
                            HasHandLuggage = true,
                            PassengerId = 23,
                            SeatNumber = "19A",
                            TotalBaggageWeightKg = 10.0
                        },
                        new
                        {
                            Id = 24,
                            FlightId = 8,
                            HasHandLuggage = true,
                            PassengerId = 24,
                            SeatNumber = "19B",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 25,
                            FlightId = 8,
                            HasHandLuggage = false,
                            PassengerId = 25,
                            SeatNumber = "19C",
                            TotalBaggageWeightKg = 8.0
                        },
                        new
                        {
                            Id = 26,
                            FlightId = 9,
                            HasHandLuggage = true,
                            PassengerId = 26,
                            SeatNumber = "20A",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 27,
                            FlightId = 9,
                            HasHandLuggage = true,
                            PassengerId = 27,
                            SeatNumber = "20B",
                            TotalBaggageWeightKg = 10.0
                        },
                        new
                        {
                            Id = 28,
                            FlightId = 9,
                            HasHandLuggage = false,
                            PassengerId = 28,
                            SeatNumber = "20C",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 29,
                            FlightId = 10,
                            HasHandLuggage = true,
                            PassengerId = 29,
                            SeatNumber = "21A",
                            TotalBaggageWeightKg = 0.0
                        },
                        new
                        {
                            Id = 30,
                            FlightId = 10,
                            HasHandLuggage = true,
                            PassengerId = 30,
                            SeatNumber = "21B",
                            TotalBaggageWeightKg = 15.0
                        });
                });

            modelBuilder.Entity("AirCompany.Domain.Model.AircraftModel", b =>
                {
                    b.HasOne("AirCompany.Domain.Model.AircraftFamily", "Family")
                        .WithMany("Models")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Flight", b =>
                {
                    b.HasOne("AirCompany.Domain.Model.AircraftModel", "Model")
                        .WithMany("Flights")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Ticket", b =>
                {
                    b.HasOne("AirCompany.Domain.Model.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirCompany.Domain.Model.Passenger", "Passenger")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("Passenger");
                });

            modelBuilder.Entity("AirCompany.Domain.Model.AircraftFamily", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("AirCompany.Domain.Model.AircraftModel", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Flight", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("AirCompany.Domain.Model.Passenger", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
